version: "3.1"

services:
  # image php
  hotspot-php:
    container_name: hotspot-php
    build:
      args:
        user: wesllycode
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../code/:/var/www
      #- ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - hotspot-nginx
    networks:
      - hot

  # nginx
  hotspot-nginx:
    container_name: hotspot-nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../code/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hot


  # db
  hotspot-db:
    container_name: hotspot-mysql
    image: mysql:latest
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    volumes:
      #- ./docker/mysql/dbdata:/var/lib/mysql
      -  ./hot-data:/var/lib/mysql/
      #- ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - hot
    ports:
      - '3388:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  hotspot-phpmyadmin:
    container_name: hotspot-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8181:80'
    networks:
      - hot
    environment:
      PMA_HOST: hotspot-db
      PMA_USER: root
      PMA_PASSWORD: root


  # redis
  hotspot-redis:
      container_name: hotspot-redis
      image: redis:latest
      ports:
        - 6379:6379
      depends_on:
        hotspot-php:
          condition: service_started
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        retries: 3
        timeout: 5s
      networks:
        - hot

  # Servidor de E-mail
  hotspot-mailhog:
      image: mailhog/mailhog:latest
      container_name: hotspot-mailhog
      ports:
         - "8003:1025"
         - "8100:8025"
      networks:
         - hot

  # queue
  hotspot-queue:
      container_name: hotspot-queue
      build:
        args:
            user: wesllycode
            uid: 1000
        context: ./
        dockerfile: Dockerfile
      restart: unless-stopped
      command: "php artisan queue:work"
      volumes:
        - ../code/:/var/www
      networks:
        - hot
      depends_on:
        - hotspot-nginx
        - hotspot-db
        - hotspot-redis

networks:
  hot:
    driver: bridge

volumes:
  code:
    driver: local
  hot-data:
    driver: local
